name: 每日新闻爬虫

on:
  schedule:
    # 在北京时间每天早上8点执行 (UTC 0:00)
    - cron: '0 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  crawl-and-commit:
    runs-on: ubuntu-latest
    # 添加权限设置
    permissions:
      contents: write

    steps:
    - name: 检出仓库
      uses: actions/checkout@v3
      with:
        # 确保能获取完整历史，便于提交
        fetch-depth: 0

    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: 安装依赖
      run: npm install

    - name: 运行爬虫脚本
      run: node news.js

    - name: 配置Git用户
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: 提交新生成的文件
      run: |
        # 获取当前日期
        DATE=$(date +"%Y%m%d")

        # 检查文件变更状态
        git status

        # 检查是否有新文件或修改
        if git diff --exit-code --quiet && [ ! -f "$DATE.md" ]; then
          echo "没有发现今日($DATE)新闻文件，跳过提交"
          exit 0
        fi

        # 添加所有变更
        git add .
        git commit -m "自动更新: $DATE 每日新闻"
        git push